language: java
jdk:
  - openjdk11

git:
  depth: false

addons:
  sonarcloud:
    organization: "kiwiproject"
    token:
      secure: "Py73Yz1I4Nai3qqEkhjQ3hjtE21CUyojAJVIOenmmbYVBIDhPjhCAzatnP4W659BoV+n2CXaOY7DDxwLEH7yMauuhHxRQwx+7voZzDSDUMW8txBCjO5Pc0/bt+RfrDdl8ajaFZRcTDzq6xCnv3nBZKutGjrovPWcDdJTIdLOcNT9Vg0XydoO5HkV53geK0eg0aFMIklYNvtgtPQbKFkL0+EqkEOjm+p2IYRlNGRw6yGPjCYBY/RRyRkGkYhjIqy2sLrWh81iTtg539y12K5yFzp9zxQz0KxidiZvVzkkr8l4lvauqPk7bAW5TaporILtU5B+VumyxeDm37Y2eU5aKWEQSxhiWywNgOZIpdvtvO5hlIqLEEOmJUUrdTwE8C/i1C++E2iVR8mOlRL2i+5LNGte53aHJb94xkD3KVeziv8N0grOIxEEoBl3mUxgaFQruxJiRz+dCIJgyEzU6w8WzjlTTAtZazXApI+zaDyKy2eXxt0eq581zcLLehmBMNLbXNycB5sHtuIWPl+kHUY4VJfoX3CHpmR9kC4Xu8z9IatqFuhfnrdVJU1RlUuLRRSU6t2kJWR1J93xZCb18/aluU7aQv7D0z867aNDeHg0P3ugnw6llAqOr7ipHBPNFjMvWXVdzFOzI5vuMHBqO0fJMXDyfWL4BrYRgCQT4TPlxmM="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=kiwiproject_dropwizard-leader-latch
